services:
  www_dev:
    container_name: chrono-debile-plus-www_dev
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    tty: true
    ports:
      - 5173:5173
    volumes:
      - .:/app
